name: Terraform workflow

# tags =/= releases! But releases will create tags and we don't want duplicate triggering.
# on: 
#   push: 
#     branches:
#       - main
#     tags:
#     - 'release*'

on:
  release:
    types: [published]

jobs:
  prod-deploy:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.7

      - name: Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Init
        id: init
        run: terraform init

      - name: Validate
        id: validate
        run: terraform validate -no-color


      - name: Terraform Plan
        run: echo "todo - terraform plan"

      - name: Terraform Apply
        run: echo "todo - terraform apply"
